import type { Metadata } from "next";

import "./globals.css";
import Client_session_provider from "@/lib/Client_session_provider";
import { Geist } from "next/font/google";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="min-h-full flex flex-col bg-black text-white">
        <Client_session_provider>
          {children}
        </Client_session_provider>
      </body>
    </html>
  );
}
